import enum

class DocumentoOrigem(enum.Enum):
    MEU_CONDOMINIO_MOBILE = 'MEU_CONDOMINIO_MOBILE'
    FATURAMENTO_JOB = 'FATURAMENTO_JOB'
    GUIAS_IMPOSTOS_JOB = 'GUIAS_IMPOSTOS_JOB'
    PROCESSAMENTO_CONTRATOS = 'PROCESSAMENTO_CONTRATOS'