from enum import Enum

class ItemDocumentoTipoTributacaoIss(Enum):
    TRIBUTADO = "TRIBUTADO"
    ISENTO = "ISENTO"
    MATERIAIS = "MATERIAIS"
    SUBEMPREITADA = "SUBEMPREITADA"
    OUTRAS_DEDUCOES = "OUTRAS_DEDUCOES"
    DESCONTO_NO_SERVICO = "DESCONTO_NO_SERVICO"
    OUTROS_VALORES = "OUTROS_VALORES"
