version: "2"

services:
  app:
    image: nasajon/django:latest
    ports:
      - "82:80"
    command: sh -c "apk update && apk --update add tzdata &&  apk add --no-cache mariadb-dev && python3 -m pip install -r requirements.txt && echo "America/Sao_Paulo" >  /etc/timezone && /entrypoint.sh"
    volumes:
      - .:/var/www/html
    env_file:
      - common.env


  memsql:
    build: ./database/inicializacao
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      - ROOT_PASSWORD=nasajon
      - LICENSE_KEY=BDI5N2M0N2M1NWNkZTQzNmFiMTU1ZTEzMjNmY2JiMDJmAAAAAAAAAAAEAAAAAAAAAAwwNQIYIN/Bhr8jwJApNG6mq1aHI3Ep0ugzTkaRAhkA4ImSi5m0cfJmYn87YfNbc8Hp8LhlAwJbAA==


  migration_diario:
    image: nasajon/django:latest
    command: sh -c "apk update && apk add --no-cache mariadb-dev && python3 -m pip install -r requirements.txt && python3 manage.py migrate diario_unico --database default"
    volumes:
      - .:/var/www/html
    env_file:
      - common.env
