from enum import Enum

class PessoaQualificacao(Enum):
    PESSOA_JURIDICA_GERAL='PESSOA_JURIDICA_GERAL'
    ORGAO_AUTARQUIA_OU_FUNDACAO_DA_ADMINISTRACAO_PUBLICA_FEDERAL='ORGAO_AUTARQUIA_OU_FUNDACAO_DA_ADMINISTRACAO_PUBLICA_FEDERAL'
    ORGAO_AUTARQUIA_OU_FUNDACAO_DA_ADMINISTRACAO_PUBLICA_ESTADUAL='ORGAO_AUTARQUIA_OU_FUNDACAO_DA_ADMINISTRACAO_PUBLICA_ESTADUAL'
    ORGAO_AUTARQUIA_OU_FUNDACAO_DA_ADMINISTRACAO_PUBLICA_MUNICIPAL='ORGAO_AUTARQUIA_OU_FUNDACAO_DA_ADMINISTRACAO_PUBLICA_MUNICIPAL'
    COOPERATIVA_DE_CREDITO='COOPERATIVA_DE_CREDITO'
    SOCIEDADE_COOPERATIVA='SOCIEDADE_COOPERATIVA'
    SOCIEDADE_COOPERATIVA_AGROPECUARIA='SOCIEDADE_COOPERATIVA_AGROPECUARIA'
    FINANCEIRA='FINANCEIRA'
    SOCIEDADE_SEGURADORA_DE_CAPITALIZACAO='SOCIEDADE_SEGURADORA_DE_CAPITALIZACAO'
    CORRETORA_AUTOMATA_DE_SEGURO='CORRETORA_AUTOMATA_DE_SEGURO'
    ENTIDADE_ABERTA_DE_PREV_COMPLEMENTAR='ENTIDADE_ABERTA_DE_PREV_COMPLEMENTAR'
    ENTIDADE_FECHADA_DE_PREV_COMPLEMENTAR='ENTIDADE_FECHADA_DE_PREV_COMPLEMENTAR'
    SOCIEDADE_DE_ECONOMIA_MISTA='SOCIEDADE_DE_ECONOMIA_MISTA'
    OUTRAS_ENTIDADES_DE_ADMINISTRACAO_PUBLICA_MUNICIPAL='OUTRAS_ENTIDADES_DE_ADMINISTRACAO_PUBLICA_MUNICIPAL'
    PESSOA_FISICA_EM_GERAL='PESSOA_FISICA_EM_GERAL'
    PESSOA_AGREGADA='PESSOA_AGREGADA'
    OUTROS='OUTROS'
    