from enum import Enum

class PessoaOrigemInformacoes(Enum):
    RECEITA_FEDERAL_BRASILEIRA='RECEITA_FEDERAL_BRASILEIRA'
    HUBSPOT='HUBSPOT'
    CONTRATO='CONTRATO'
    NOTA_MERCADORIA='NOTA_MERCADORIA'
    NOTA_SERVICO='NOTA_SERVICO'
    OUTROS='OUTROS'
    
