# Generated by Django 2.2.5 on 2020-01-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0001_Version201906241200'),
    ]

    operations = [
        migrations.RunSQL(
            """
            alter table documento_fiscal add column data_criacao date;
            """,
            ""  # Aqui ficaria o SQL para reverter a migration
        ),
        migrations.RunSQL(
            """
            alter table documento_fiscal add column url_documento varchar(500);
            """,
            ""  # Aqui ficaria o SQL para reverter a migration
        ),
        migrations.RunSQL(
            """
            alter table documento_fiscal add column numero_contrato varchar(50);
            """,
            ""  # Aqui ficaria o SQL para reverter a migration
        )
    ]
