# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0003_Version201907041840'),
    ]

    operations = [
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'aa172dba-f0be-469b-85f3-057cf8b6578f', '1', 'ATIVO', '1', 'D', 2019, 0, 'null');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '79be1896-b3fa-4c69-8892-661139d0310a', '1.1', 'ATIVO CIRCULANTE', '1', 'D', 2019, 0, 'aa172dba-f0be-469b-85f3-057cf8b6578f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '448da6dd-0b46-43f4-963b-30cb4b5651d6', '1.1.1', 'DISPONIBILIDADES', '1', 'D', 2019, 0, '79be1896-b3fa-4c69-8892-661139d0310a');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '9728abcf-a01d-410e-9ebd-0657138e900a', '1.1.1.01', 'CAIXA GERAL', '1', 'D', 2019, 0, '448da6dd-0b46-43f4-963b-30cb4b5651d6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'ae5f5401-3ee0-4d98-82f2-05acb5ea0f39', '1.1.1.02', 'BANCOS C/ MOVIMENTO', '1', 'D', 2019, 0, '448da6dd-0b46-43f4-963b-30cb4b5651d6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '26054a4b-6e8c-4c88-80b7-9060f863b6ae', '1.1.1.03', 'APLICAÇÕES DE LIQUIDEZ IMEDIATA', '1', 'D', 2019, 0, '448da6dd-0b46-43f4-963b-30cb4b5651d6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '6c65f2fb-1602-436d-a8e7-9b843eec65fe', '1.1.2', 'CRÉDITOS E VALORES', '1', 'D', 2019, 0, '79be1896-b3fa-4c69-8892-661139d0310a');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'cb717539-01ec-4795-8c28-30f54f00d64d', '1.1.2.01', 'COTAS CONDOMINIAIS A RECEBER', '1', 'D', 2019, 0, '6c65f2fb-1602-436d-a8e7-9b843eec65fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'e68a6831-bad2-4fcf-a3da-0d9535a223db', '1.1.2.02', 'COTAS CONDOMINIAIS EM ATRASO', '1', 'D', 2019, 0, '6c65f2fb-1602-436d-a8e7-9b843eec65fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'b8b5922f-34dd-4453-853b-570c66119665', '1.1.2.03', 'COTAS EXTRAS CONDOMINIAIS A RECEBER', '1', 'D', 2019, 0, '6c65f2fb-1602-436d-a8e7-9b843eec65fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'a9b992d8-3cc6-48f9-947b-4a6f2f32b6cd', '1.1.2.04', 'COTAS EXTRAS CONDOMINIAIS EM ATRASO', '1', 'D', 2019, 0, '6c65f2fb-1602-436d-a8e7-9b843eec65fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '35c89f46-fc9c-4d8c-8cbe-df0a289a2e12', '1.1.2.08', '(-) PERDAS ESTIMADAS C/ CRÉDITOS', '1', 'C', 2019, 0, '6c65f2fb-1602-436d-a8e7-9b843eec65fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c67dd893-ef53-4573-9fab-de76b98cfa19', '1.1.2.09', '(-) CRÉDITOS BAIXADOS', '1', 'C', 2019, 0, '6c65f2fb-1602-436d-a8e7-9b843eec65fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '51c2b7b2-3a75-4eb0-9d99-394b2185d9b5', '1.2', 'ATIVO NÃO CIRCULANTE', '1', 'D', 2019, 0, 'aa172dba-f0be-469b-85f3-057cf8b6578f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'd4903962-a2fe-4085-a8ab-66bcaf753748', '1.2.1', 'REALIZÁVEL A LONGO PRAZO', '1', 'D', 2019, 0, '51c2b7b2-3a75-4eb0-9d99-394b2185d9b5');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '570dccf3-83e1-411c-a4b3-d746c8dd3e00', '1.2.2', 'INVESTIMENTOS', '1', 'D', 2019, 0, '51c2b7b2-3a75-4eb0-9d99-394b2185d9b5');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'af18acc3-9952-4c8e-91f6-568b6c27cdbe', '1.2.2.01', 'SISTEMA FINANCEIRO NACIONAL', '1', 'D', 2019, 0, '570dccf3-83e1-411c-a4b3-d746c8dd3e00');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '0ad0d711-a867-4cc2-af7b-5fea4cf1127a', '1.2.3', 'IMOBILIZADO', '1', 'D', 2019, 0, '51c2b7b2-3a75-4eb0-9d99-394b2185d9b5');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '980d7e43-9ad2-4296-a702-0eeda805af52', '1.2.3.03', 'INSTALAÇÕES', '1', 'D', 2019, 0, '0ad0d711-a867-4cc2-af7b-5fea4cf1127a');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'e51befe8-5705-4f63-b86c-8b38e1c06096', '1.2.3.09', '(-) DEPRECIAÇÕES ACUMULADAS', '1', 'C', 2019, 0, '0ad0d711-a867-4cc2-af7b-5fea4cf1127a');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '5bde3e84-927b-40ca-87b5-9394b60ca9c1', '1.3', 'ATIVO COMPENSADO', '1', 'D', 2019, 0, 'aa172dba-f0be-469b-85f3-057cf8b6578f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '9873211a-3bcb-4d9a-b1a9-856cef1fcec3', '1.3.1', 'CONTAS DE COMPENSAÇÃO DO ATIVO', '1', 'D', 2019, 0, '5bde3e84-927b-40ca-87b5-9394b60ca9c1');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '0dfcef96-5c93-4712-be1c-ae55dcb7938b', '2', 'PASSIVO', '2', 'C', 2019, 0, 'null');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '62edf6b7-57b3-4f45-bf03-6157138a65b6', '2.1', 'PASSIVO CIRCULANTE', '2', 'C', 2019, 0, '0dfcef96-5c93-4712-be1c-ae55dcb7938b');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '8be00b09-3bc8-431b-ac2b-031a88d8954c', '2.1.1', 'EMPRÉSTIMOS E FINANCIAMENTOS', '2', 'C', 2019, 0, '62edf6b7-57b3-4f45-bf03-6157138a65b6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '77eb85b0-1add-4fb5-8d1c-9b5db579aa26', '2.1.1.01', 'BANCOS C/ EMPRÉSTIMOS', '2', 'C', 2019, 0, '8be00b09-3bc8-431b-ac2b-031a88d8954c');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'd21959d4-a03b-4320-9784-721828a9e959', '2.1.1.02', 'BANCOS C/ FINANCIAMENTOS', '2', 'C', 2019, 0, '8be00b09-3bc8-431b-ac2b-031a88d8954c');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '95a7b8d7-b229-4b43-bf28-fdf1ff17698f', '2.1.2', 'OBRIGAÇÕES SOCIAIS', '2', 'C', 2019, 0, '62edf6b7-57b3-4f45-bf03-6157138a65b6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'a1f5c99b-3e44-4d5f-902f-1e35cae72ef5', '2.1.2.01', 'OBRIGAÇÕES PREVIDENCIÁRIAS', '2', 'C', 2019, 0, '95a7b8d7-b229-4b43-bf28-fdf1ff17698f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'a730699f-edbf-4260-a4e6-c1ed1354267b', '2.1.2.01.0001', 'INSS A RECOLHER', '2', 'C', 2019, 0, 'a1f5c99b-3e44-4d5f-902f-1e35cae72ef5');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '9b74a007-ef69-4228-8351-e976b5458da6', '2.1.2.01.0002', 'FGTS A RECOLHER', '2', 'C', 2019, 0, 'a1f5c99b-3e44-4d5f-902f-1e35cae72ef5');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '9cf11374-59c7-4e26-a4fc-85b533753fda', '2.1.2.02', 'OBRIGAÇÕES TRIBUTÁRIAS', '2', 'C', 2019, 0, '95a7b8d7-b229-4b43-bf28-fdf1ff17698f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '54affa20-dd49-41f2-b163-4e9905f68a32', '2.1.2.02.0001', 'CONTRIBUIÇÃO CONFEDERATIVA A PAGAR', '2', 'C', 2019, 0, '9cf11374-59c7-4e26-a4fc-85b533753fda');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '2eab01be-0349-4371-98c5-02540530ffa4', '2.1.2.02.0002', 'CONTRIBUIÇÃO SINDICAL A RECOLHER', '2', 'C', 2019, 0, '9cf11374-59c7-4e26-a4fc-85b533753fda');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '1f6cf976-d978-4834-8af7-f735e53416d8', '2.1.2.02.0003', 'IMPOSTO DE RENDA RETIDO NA FONTE A RECOLHER', '2', 'C', 2019, 0, '9cf11374-59c7-4e26-a4fc-85b533753fda');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '367ed0d9-ab5f-4cef-98e3-1ed995a7a168', '2.1.2.02.0004', 'PIS S/ FOLHA A PAGAR', '2', 'C', 2019, 0, '9cf11374-59c7-4e26-a4fc-85b533753fda');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '42c8d7fe-7762-4605-ab9f-99975fc394fe', '2.1.2.03', 'OBRIGAÇÕES TRABALHISTAS', '2', 'C', 2019, 0, '95a7b8d7-b229-4b43-bf28-fdf1ff17698f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '56293c25-a3ec-434d-8e08-cb36e00a94f7', '2.1.2.03.0001', '13.º SALÁRIOS A PAGAR', '2', 'C', 2019, 0, '42c8d7fe-7762-4605-ab9f-99975fc394fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c08a9c95-b38d-4f5c-a235-fae6130486c9', '2.1.2.03.0002', 'FÉRIAS A PAGAR', '2', 'C', 2019, 0, '42c8d7fe-7762-4605-ab9f-99975fc394fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '301fd102-c78f-4112-84da-198c21d2781f', '2.1.2.03.0003', 'SALÁRIOS E ORDENADOS A PAGAR', '2', 'C', 2019, 0, '42c8d7fe-7762-4605-ab9f-99975fc394fe');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '2d5d686e-a43b-4c37-9335-7d466ddf55f3', '2.1.2.04', 'FORNECEDORES', '2', 'C', 2019, 0, '95a7b8d7-b229-4b43-bf28-fdf1ff17698f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '385a2d5a-4934-448b-b488-0640acbc08bb', '2.1.3', 'PROVISÕES P/ CONTINGÊNCIAS', '2', 'C', 2019, 0, '62edf6b7-57b3-4f45-bf03-6157138a65b6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '3050bbc3-109c-4544-a5e8-63a6c64d6a8f', '2.1.3.01', 'PROVISÕES DE 13.º SALÁRIOS', '2', 'C', 2019, 0, '385a2d5a-4934-448b-b488-0640acbc08bb');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '988595a5-bc23-4376-b6f2-a99b79cd17f2', '2.1.3.01.0001', 'PROVISÃO DE 13.º SALÁRIOS A PAGAR', '2', 'C', 2019, 0, '3050bbc3-109c-4544-a5e8-63a6c64d6a8f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '202b47ec-3d2c-4328-ab75-8bc8ef497976', '2.1.3.01.0002', 'PROVISÃO DO FGTS A PAGAR S/ 13.º SALÁRIOS', '2', 'C', 2019, 0, '3050bbc3-109c-4544-a5e8-63a6c64d6a8f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '0cbaaa6a-2e89-4b68-a9f1-078d3300ac8c', '2.1.3.01.0003', 'PROVISÃO DO INSS A PAGAR S/ 13.º SALÁRIOS', '2', 'C', 2019, 0, '3050bbc3-109c-4544-a5e8-63a6c64d6a8f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'b28eb364-c970-4db7-ab52-afaa74c81d55', '2.1.3.02', 'PROVISÕES DE FÉRIAS', '2', 'C', 2019, 0, '385a2d5a-4934-448b-b488-0640acbc08bb');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '870a45df-ecb8-435e-8369-ab48de135c49', '2.1.3.02.0001', 'PROVISÃO DE FÉRIAS A PAGAR', '2', 'C', 2019, 0, 'b28eb364-c970-4db7-ab52-afaa74c81d55');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '8e801173-50bf-427c-badd-d8185be8ba91', '2.1.3.02.0002', 'PROVISÃO DO FGTS A PAGAR S/ FÉRIAS', '2', 'C', 2019, 0, 'b28eb364-c970-4db7-ab52-afaa74c81d55');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '11b352b2-f94f-4e00-a85e-17b0f9b2e339', '2.1.3.02.0003', 'PROVISÃO DO INSS A PAGAR S/ FÉRIAS', '2', 'C', 2019, 0, 'b28eb364-c970-4db7-ab52-afaa74c81d55');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '3f7d9bbd-9434-4ad5-a66e-edecae4c69ac', '2.2', 'PASSIVO NÃO CIRCULANTE', '2', 'C', 2019, 0, '0dfcef96-5c93-4712-be1c-ae55dcb7938b');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '2553a3ca-582c-4e4c-a4ce-314e6849c445', '2.2.1', 'EXIGÍVEL A LONGO PRAZO', '2', 'C', 2019, 0, '3f7d9bbd-9434-4ad5-a66e-edecae4c69ac');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'cd428f1b-78af-44fb-9c93-2229d82107ed', '2.3', 'PATRIMÔNIO LÍQUIDO', '2', 'C', 2019, 0, '0dfcef96-5c93-4712-be1c-ae55dcb7938b');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'cd97475a-2cf4-47f0-a292-90d9ec0876ee', '2.3.1', 'PATRIMÔNO SOCIAL', '2', 'C', 2019, 0, 'cd428f1b-78af-44fb-9c93-2229d82107ed');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '19d7b7f0-3ae7-4a92-b1be-5a714c097d19', '2.3.1.01', 'BENS PATRIMONIAIS', '2', 'C', 2019, 0, 'cd97475a-2cf4-47f0-a292-90d9ec0876ee');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '7ee07780-4118-4cb1-8967-87a71b0fdee9', '2.3.1.02', 'SUPERÁVIT PATRIMONIAL', '2', 'C', 2019, 0, 'cd97475a-2cf4-47f0-a292-90d9ec0876ee');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '22e87887-dfe1-4bc8-95fa-e4c113822591', '2.3.1.03', '(-) DÉFICIT PATRIMONIAL', '2', 'D', 2019, 0, 'cd97475a-2cf4-47f0-a292-90d9ec0876ee');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '5557ebd5-7737-4ea9-a959-46079a26a06d', '2.3.2', 'FUNDOS DE RESERVA', '2', 'C', 2019, 0, 'cd428f1b-78af-44fb-9c93-2229d82107ed');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'eb4851a1-0413-4c78-9101-f3678506adf2', '2.3.2.01', 'FUNDO DE RESERVA P/ CONTINGÊNCIAS', '2', 'C', 2019, 0, '5557ebd5-7737-4ea9-a959-46079a26a06d');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '4fc01e08-6910-4cfc-b9c0-46a2dc92442c', '2.3.2.02', 'FUNDO DE RESERVA P/ INDENIZAÇÕES TRABALHISTAS', '2', 'C', 2019, 0, '5557ebd5-7737-4ea9-a959-46079a26a06d');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '52d5aa22-25c3-4f33-8c3a-a87b6fde9373', '2.4', 'PASSIVO COMPENSADO', '2', 'C', 2019, 0, '0dfcef96-5c93-4712-be1c-ae55dcb7938b');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'a679a51c-a455-4b2f-8c8a-f0afef468f7f', '2.4.1', 'CONTAS DE COMPENSAÇÃO DO PASSIVO', '2', 'C', 2019, 0, '52d5aa22-25c3-4f33-8c3a-a87b6fde9373');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '9b01c4fd-a0ee-4fb7-98f2-01225e1185ff', '3', 'CONTAS DE RESULTADOS CREDORAS', '3', 'D', 2019, 0, 'null');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '330dc100-7a70-4d01-a981-e27cef666cde', '3.1', 'RECEITAS', '3', 'D', 2019, 0, '9b01c4fd-a0ee-4fb7-98f2-01225e1185ff');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '2154d670-5b9a-4dec-afd3-5fedee47f843', '3.1.1', 'RECEITAS FINANCEIRAS', '3', 'D', 2019, 0, '330dc100-7a70-4d01-a981-e27cef666cde');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '53699c72-e05f-4be0-af38-bf553db91bdf', '3.1.1.01', 'RECEITAS DE MULTA E ACRÉSCIMOS MORATÓRIOS', '3', 'D', 2019, 0, '2154d670-5b9a-4dec-afd3-5fedee47f843');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'ba516774-2d5d-45d0-b677-ac67f0e1eace', '3.1.1.02', 'RENDAS DE INVESTIMENTOS TEMPORÁRIOS NO SFN (sistema financeiro de habitação)', '3', 'D', 2019, 0, '2154d670-5b9a-4dec-afd3-5fedee47f843');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c077e425-8070-4edd-8c77-ac023a526f1a', '3.1.1.03', 'LUCRO NA VENDA DE INVESTIMENTOS TEMPORÁRIOS', '3', 'D', 2019, 0, '2154d670-5b9a-4dec-afd3-5fedee47f843');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '7b0c6183-a24f-4313-8b88-3c7b46e951be', '4', 'CONTAS DE RESULTADO DEVEDORAS', '4', 'C', 2019, 0, 'null');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '6ff44066-8793-405d-9069-8cce4fb8b783', '4.1', 'DESPESAS', '4', 'C', 2019, 0, '7b0c6183-a24f-4313-8b88-3c7b46e951be');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '17046e34-283d-4e31-a56f-aeeae1ca5311', '4.1.1', 'DESPESAS CONDOMINIAIS', '4', 'C', 2019, 0, '6ff44066-8793-405d-9069-8cce4fb8b783');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '57c56d1a-6da8-494c-aa7a-70478b21fba2', '4.1.1.01', 'DESPESAS C/ SALÁRIOS E ENCARGOS SOCIAIS DOS EMPREGADOS', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'f3117e68-d18a-4d63-9e67-e2c135a283c0', '4.1.1.01.0001', 'ADICIONAL NOTURNO', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'eb536df6-0580-499f-b9fd-7d6c7325b89c', '4.1.1.01.0002', 'ANUÊNIO', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'eabffe9e-80d0-485a-8d06-2f13232285de', '4.1.1.01.0003', 'ASSISTÊNCIA MÉDICA E SOCIAL', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'ed71459c-daa1-4eff-9fcc-a27c8a24c959', '4.1.1.01.0004', 'ASSISTÊNCIA ODONTOLÓGICA', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '31baf967-1f2b-48ab-8bcb-74290bf5a4f3', '4.1.1.01.0005', 'AVISO PRÉVIO E OUTRAS INDENIZAÇÕES TRABALHISTAS', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '6ca7dca9-6d80-4af7-9938-cc7e9c67c3db', '4.1.1.01.0006', 'DESCANSO SEMANAL REMUNERADO (DSR)', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '97df8e69-4a42-4d2f-962b-7e5fbc4fa6fc', '4.1.1.01.0007', 'EQUIPAMENTOS DE PROTEÇÃO INDIVIDUAL - EPI', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '45e40939-e3e0-4d53-9afb-db784e174ee9', '4.1.1.01.0008', 'FARMÁCIA E MEDICAMENTOS', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '8b0aad83-08e2-457f-b574-cc29e9615b08', '4.1.1.01.0009', 'FÉRIAS C/ ABONO', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'b60a4784-3e29-443f-bbd3-b2c9c4f35b38', '4.1.1.01.0010', 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO - FGTS', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '931b45ea-da4a-40d2-bbe4-1cb096b4826b', '4.1.1.01.0011', 'GRATIFICAÇÃO NATALINA (13.º SALÁRIOS)', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'ae0d5019-2b77-42c7-8020-355f20e86fb1', '4.1.1.01.0012', 'HORAS EXTRAS', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '1d55c20a-98c5-4063-9148-62d69fd2b2ef', '4.1.1.01.0013', 'INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'ff0a912f-d161-4158-b46b-aa2472a0f7ae', '4.1.1.01.0014', 'PROGRAMA DE ALIMENTAÇÃO DO TRABALHADOR - PAT', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '069f8961-0d8d-4fde-99db-a76a4aa1dcb9', '4.1.1.01.0015', 'SALÁRIOS E ORDENADOS', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '02b9f289-9f34-4fa5-a650-164654c3cbb6', '4.1.1.01.0016', 'UNIFORMES', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '2541b804-91d6-4435-95d4-8b205c73bd03', '4.1.1.01.0017', 'VALE TRANSPORTE - VT', '4', 'C', 2019, 0, '57c56d1a-6da8-494c-aa7a-70478b21fba2');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c0013198-2653-4eab-936f-eb3a03526403', '4.1.1.02', 'DESPESAS DE ADMINISTRAÇÃO DO CONDOMÍNIO', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '12a776a5-2c01-4ede-9079-6047d12cec64', '4.1.1.03', 'DESPESAS C/ PRESTAÇÃO DE SERVIÇOS', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'e94731af-597a-4979-8c4b-ce975da36072', '4.1.1.04', 'DESPESAS C/ SEGUROS', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '55b9ba4b-3176-4e79-aa40-26b1c374d075', '4.1.1.04.0001', 'SEGURO DE ACIDENTE DE TRABALHO', '4', 'C', 2019, 0, 'e94731af-597a-4979-8c4b-ce975da36072');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '3c6f1bbb-d46c-4d00-80cc-888d9439b0fa', '4.1.1.04.0002', 'SEGURO DE VIDA EM GRUPO', '4', 'C', 2019, 0, 'e94731af-597a-4979-8c4b-ce975da36072');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '926b383e-cbf5-40e2-92ba-47c5a8187eb6', '4.1.1.05', 'DESPESAS C/ LIMPEZA E CONSERVAÇÃO', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '6ac2120b-dd4d-4646-9d96-6aa745a7b6e9', '4.1.1.05.0001', 'HIGIÊNE E LIMPEZA', '4', 'C', 2019, 0, '926b383e-cbf5-40e2-92ba-47c5a8187eb6');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'daff5c14-3f81-4810-bf23-d0c8f477ce59', '4.1.1.06', 'DESPESAS C/ MANUTENÇÃO E CONSERVAÇÃO DE EQUIPAMENTOS', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c9afbe0f-c8f0-4738-9215-86b7a5105a4d', '4.1.1.07', 'DESPESAS DE ÁGUA E ESGOTO', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '54c27cc6-41ff-4f28-a4f9-a1ce3ad10106', '4.1.1.07.0001', 'CONSUMO DE ÁGUA', '4', 'C', 2019, 0, 'c9afbe0f-c8f0-4738-9215-86b7a5105a4d');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '89fdf67d-2d1a-4f34-a65a-48d761f46134', '4.1.1.08', 'DESPESAS DE LUZ, GÁS, TELEFONE, ANTENA COLETIVA', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '50ffbc1d-9056-497e-88cf-6a4aec19d20f', '4.1.1.08.0001', 'COMUNICAÇÕES TELEFÔNICAS', '4', 'C', 2019, 0, '89fdf67d-2d1a-4f34-a65a-48d761f46134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c3628f7d-bfa1-426f-85c0-263b0f79f774', '4.1.1.08.0002', 'CONSUMO DE ENERGIA ELÉTRICA', '4', 'C', 2019, 0, '89fdf67d-2d1a-4f34-a65a-48d761f46134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'bf8ce236-683a-47e7-b7a0-c3e2e1f34e09', '4.1.1.08.0003', 'CONSUMO DE GÁS', '4', 'C', 2019, 0, '89fdf67d-2d1a-4f34-a65a-48d761f46134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '76ab3995-0744-4a7b-8d13-79363f669359', '4.1.1.08.0004', 'USO DA ANTENA COLETIVA', '4', 'C', 2019, 0, '89fdf67d-2d1a-4f34-a65a-48d761f46134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '95d0f3d4-3e98-4394-a1d1-07e6a8417134', '4.1.1.09', 'DESPESAS C/ IMPOSTOS E TAXAS', '4', 'C', 2019, 0, '17046e34-283d-4e31-a56f-aeeae1ca5311');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'cf066349-b57c-480b-9981-c38e1c8c0b9f', '4.1.1.09.0001', 'IMPOSTO S/ PROPRIEDADE TERRITORIAL URBANA - IPTU', '4', 'C', 2019, 0, '95d0f3d4-3e98-4394-a1d1-07e6a8417134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c31b8445-5196-4c21-88f5-2f93f15af6a9', '4.1.1.09.0002', 'TAXA DA COLETA DE LIXO', '4', 'C', 2019, 0, '95d0f3d4-3e98-4394-a1d1-07e6a8417134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'fac0106f-204a-452d-aca3-8081518f764d', '4.1.1.09.0003', 'TAXA DE VISTORIA DOS BOMBEIROS', '4', 'C', 2019, 0, '95d0f3d4-3e98-4394-a1d1-07e6a8417134');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '05466f5e-9cb3-41f1-9b3f-f372b53aa0ea', '4.1.2', 'DESPESAS FINANCEIRAS E FISCAIS', '4', 'C', 2019, 0, '6ff44066-8793-405d-9069-8cce4fb8b783');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c80d009e-328d-4fe7-b33b-bebb3951d6d9', '4.1.2.01', 'PREJUÍZO NA VENDA DE INVESTIMENTOS TEMPORÁRIOS NO S.F.N.', '4', 'C', 2019, 0, '05466f5e-9cb3-41f1-9b3f-f372b53aa0ea');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '947e7eed-4257-4818-bf13-dee3538b0a6f', '4.1.2.02', 'JUROS E DESPESAS BANCÁRIAS', '4', 'C', 2019, 0, '05466f5e-9cb3-41f1-9b3f-f372b53aa0ea');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'd75e160a-6eb2-49bb-81ae-f67831a1ae02', '4.1.2.02.0001', 'IOF - DÉBITO AUTOMÁTICO', '4', 'C', 2019, 0, '947e7eed-4257-4818-bf13-dee3538b0a6f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '978d3007-741f-4d51-9fcb-878d4a82a61e', '4.1.2.02.0002', 'JUROS E COMISSÕES BANCÁRIAS', '4', 'C', 2019, 0, '947e7eed-4257-4818-bf13-dee3538b0a6f');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', '523ca5fe-dece-4b4a-bb60-61ec25d1b83b', '4.1.2.03', 'DESPESAS C/ MULTAS E INFRAÇÕES FISCAIS', '4', 'C', 2019, 0, '05466f5e-9cb3-41f1-9b3f-f372b53aa0ea');",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
