# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0006_Version201907121301'),
    ]

    operations = [

        migrations.RunSQL("""
                update pessoas set codigo='5697458214785698', nomefantasia='HOMOLOGACAO' where codigo = 'HOMOLOGACAO';
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
                update estabelecimentos set pessoa='60375e29-5a64-4709-ab64-8435b38bfa6a';
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
