# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0007_Version201907121705'),
    ]

    operations = [

        migrations.RunSQL("""
                 CREATE TABLE plano_contas_segmentos (
                    plano_contas varchar(30),
                    segmento int not null,
                    tributacao int not null,                   
                    CONSTRAINT definicoes_lancamentos_PK PRIMARY KEY (plano_contas, segmento, tributacao)
                );
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
