# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0011_Version201907160733'),
    ]

    operations = [

        migrations.RunSQL("""
                alter table diario_universal add column codigo_transacao varchar(60);
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),



    ]
