# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0021_Version201907311604'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE associacao_contas_personalizadas (
                conta_personalizada varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                conta_contabil varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                empresa varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                tipo_associacao int(11) NOT NULL,
                PRIMARY KEY (conta_contabil,empresa, conta_personalizada)
              );              
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
                CREATE TABLE contas_personalizadas (
                    plano_contas_personalizado varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                    conta_personalizada varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                    codigo varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                    nome varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                    reduzido varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                    natureza varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'O',
                    exercicio int(11) NOT NULL,
                    tenant int(11) NOT NULL
                    /*!90618 , SHARD KEY () */ 
                  );
                  
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
            CREATE TABLE filtro_associacao_contas (
                filtro_associacao_conta varchar(36) not null,
                dimensao int(11) NOT NULL,
                tipo_filtro int(11) NOT NULL,
                conta_personalizada varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                conta_contabil varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                ordem int(11) NOT NULL,
                valor varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                PRIMARY KEY (filtro_associacao_conta)
              );
                            
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
            CREATE TABLE filtro_associacao_contas_valor (
                filtro_associacao_contas_valor varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                filtro_associacao_conta varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                valor varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                PRIMARY KEY (filtro_associacao_contas_valor)
              );                           
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
            CREATE TABLE contas_personalizadas_cache (
                empresa varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                ano varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                codigo varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                nome varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                conta_contabil varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                conta_financeira varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                forma_pagamento varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                projeto varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                renegociacao varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                trabalhador varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                departamento varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                participante varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                rateio decimal(5,4) not null default 1,           
                tenant int(11) NOT NULL
                /*!90618 , SHARD KEY () */ 
              );
                            
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
              ALTER TABLE pessoas ADD indice_contabil INT NULL;                              
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
