# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0030_Version201908141213'),
    ]

    operations = [
        migrations.RunSQL("""alter table info_cobranca add column nome_cliente varchar(500);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column cpf_cliente varchar(30);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_logradouro varchar(500);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_numero varchar(500);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_complemento varchar(500);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_bairro varchar(50);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_cidade varchar(50);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_estado varchar(50);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column endereco_cep varchar(30);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
