# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0031_Version201908151412'),
    ]

    operations = [
        migrations.RunSQL("""ALTER TABLE diario_unico ADD info_pagamento varchar(36) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD info_cobranca varchar(36) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
