# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0032_Version201908210846'),
    ]

    operations = [
        migrations.RunSQL("""
            update definicoes_lancamentos set formula_data='vencimento' where formula_data='data_pagamento' 
                and evento in ('APROPRIACAO_CONTA_AGUA', 'APROPRIACAO_CONTA_ENERGIA', 'APROPRIACAO_CONTA_GAS', 'PREVISAO_CONTA_AGUA',
                                'PREVISAO_CONTA_ENERGIA','PREVISAO_CONTA_GAS', 'PREVISAO_COTA_CONDOMINIAL' );""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
            update definicoes_info_pagamento set formula_vencimento='vencimento' where evento in ('APROPRIACAO_CONTA_AGUA', 'APROPRIACAO_CONTA_ENERGIA', 'APROPRIACAO_CONTA_GAS');""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
            update definicoes_lancamentos 
            set conta='1.1.1.01' 
            where evento='APROPRIACAO_COTA_CONDOMINIAL' and numero=2 and ordem=1;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
            update definicoes_lancamentos 
            set conta='1.1.2.01' 
            where evento='APROPRIACAO_COTA_CONDOMINIAL' and numero=2 and ordem=2;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
            update definicoes_lancamentos 
            set conta='1.1.1.01' 
            where evento='PAGAMENTO_COTA_CONDOMINIAL' and numero=1 and ordem=1;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
            update definicoes_lancamentos 
            set conta='1.1.2.01' 
            where evento='PAGAMENTO_COTA_CONDOMINIAL' and numero=1 and ordem=2;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
            update definicoes_lancamentos 
            set conta='1.1.1.01' 
            where evento='PREVISAO_COTA_CONDOMINIAL' and numero=2 and ordem=1;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
            update definicoes_lancamentos 
            set conta='1.1.2.01' 
            where evento='PREVISAO_COTA_CONDOMINIAL' and numero=2 and ordem=2;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
