# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0035_Version201908271212'),
    ]

    operations = [
        migrations.RunSQL("""
    INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('4f5a2c6c-b1e1-402d-8f20-1f3bd0cd55d3','APROPRIACAO_CONTA_NFSE',1,'D',1,'4.1.1.03','Despesa de aquisicao de servico','valor',1,'CONDOMINIO',47,0,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('85ee8556-3091-444a-9ad6-637e9c0219f0','APROPRIACAO_CONTA_NFSE',1,'C',2,'2.1.2.04','aquisicao de servico','valor',1,'CONDOMINIO',47,0,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('72da6557-eaa6-40a8-8db5-7f8fada43765','APROPRIACAO_CONTA_NFSE',2,'D',1,'2.1.2.04','Pagamento de aquisicao de servico','valor',1,'CONDOMINIO',47,2,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('69c5b413-8e76-4931-9675-2e2668ab6e90','APROPRIACAO_CONTA_NFSE',2,'C',2,'1.1.1.01','Pagamento de aquisicao de servico','valor',1,'CONDOMINIO',47,2,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('fc42eb67-2259-4158-9b2d-9788c147c556','PREVISAO_CONTA_NFSE',1,'D',1,'4.1.1.03','Despesa de aquisicao de servico','valor',1,'CONDOMINIO',47,2,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('f2116d03-8b95-48bf-9e72-86a5f08c299c','PREVISAO_CONTA_NFSE',1,'C',2,'2.1.2.04','aquisicao de servico','valor',1,'CONDOMINIO',47,2,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('baf3afc3-e449-439f-be24-1f62c75ac27e','PREVISAO_CONTA_NFSE',2,'D',1,'2.1.2.04','Pagamento de aquisicao de servico','valor',1,'CONDOMINIO',47,2,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('225b88e8-3ba2-43cc-9375-5ea7b33d7507','PREVISAO_CONTA_NFSE',2,'C',2,'1.1.1.01','Pagamento de aquisicao de servico','valor',1,'CONDOMINIO',47,2,'emissao');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('a9379ed3-cf62-4211-850f-278f5539b179','PAGAMENTO_CONTA_NFSE',2,'D',1,'2.1.2.04','Pagamento de aquisicao de servico','valor',1,'CONDOMINIO',47,0,'data_pagamento');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""
INSERT INTO definicoes_lancamentos (definicao_lancamento,evento,numero,natureza,ordem,conta,historico,formula,diario_subtipo,plano_contas,tenant,situacao,formula_data)
    VALUES ('5090575f-fea4-4371-9d69-ea9d931735d3','PAGAMENTO_CONTA_NFSE',2,'C',2,'1.1.1.01','Pagamento de aquisicao de servico','valor',1,'CONDOMINIO',47,0,'data_pagamento');
    """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

    ]
