# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0036_Version201909021533'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO enderecos
                (cidade, bairro, cep, tipologradouro, logradouro, numero, complemento, pessoa, cobranca)
                VALUES('Rio de Janeiro', 'Centro', '20040090', '0', 'Rua dos Romeiros', '93', NULL, 'e323f2e3-cfe9-47d1-a916-0daa8b28f85b', 1);
        """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
        INSERT INTO enderecos
                (cidade, bairro, cep, tipologradouro, logradouro, numero, complemento, pessoa, cobranca)
                VALUES('Rio de Janeiro', 'Centro', '20040080', '0', 'Rua da Assembleia', '6', NULL, '4acecb0c-c867-43ec-bbec-12808dfff231', 1);
        """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
        INSERT INTO enderecos
                (cidade, bairro, cep, tipologradouro, logradouro, numero, complemento, pessoa, cobranca)
                VALUES('Rio de Janeiro', 'Centro', '20040040', '0', 'Rua da Assembleia', '35', NULL, '7f0f1ba2-56f4-4210-b9b6-219467f07173', 1);
        """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
        INSERT INTO enderecos
                (cidade, bairro, cep, tipologradouro, logradouro, numero, complemento, pessoa, cobranca)
                VALUES('Rio de Janeiro', 'Centro', '20040030', '0', 'Rua do Ouvidor', '60', NULL, 'e226b89e-60f3-402d-b0c0-8074490b604d', 1);
        """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
