# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0038_Version201909121212'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE tabela_seriais (
            identificacao varchar(100) NOT NULL,
            serial INT NOT NULL DEFAULT 1
        );""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
