# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0039_Version201909131036'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE if not exists time_service (
            data_hora_gravada DATETIME NOT NULL,
            ultima_alteracao DATETIME NOT NULL
        );""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
