# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0046_Version201909301212'),
    ]

    operations = [
        migrations.RunSQL("""alter table pessoas add column ativo_fornecedor int default 0""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
