# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0047_Version201910021045'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE grupo_empresarial(
        grupo_empresarial varchar(36) NOT NULL,
        codigo varchar(20) NOT NULL,
        tenant INT NOT NULL
        )""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table empresas add column grupo_empresarial character varying(36) not null""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""insert into grupo_empresarial (grupo_empresarial, codigo, tenant) select '5b857e2b-f715-4ef2-93f5-55d73f6bd618', codigo, tenant from empresas""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
