# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0051_Version201911281230'),
    ]

    operations = [
        migrations.RunSQL("""alter
                        VIEW vw_timeserver AS select
                        coalesce((select adddate(data_hora_gravada, interval timestampdiff(second, ultima_alteracao, now()) second) as tempo
                        from time_service limit 1), now()) as tempo""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
