# Generated by Django 2.2.5 on 2020-01-24 14:49

from django.db import migrations
import os


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0057_Version202001151607'),
    ]

    operations = [
        # Usar para o MariaDB columnstore se for preciso configurar por migration
        
        migrations.RunSQL("""CREATE or replace FUNCTION colocar_mascara(conta_pai varchar(50), mascara varchar(50), numero varchar(50)) 
                            RETURNS VARCHAR(50)
                                BEGIN
                                    RETURN CONCAT(conta_pai,'.',LPAD(numero,length(SUBSTRING_INDEX(SUBSTRING(mascara,length(conta_pai)+2,50),'.',1)),'0'));
                                END ;""" if os.getenv("diario_banco", "memsql") == "mariadb" else """CREATE or replace FUNCTION colocar_mascara(conta_pai varchar(50), mascara varchar(50), numero varchar(50)) 
                            RETURNS VARCHAR(50) AS
                                BEGIN
                                    RETURN CONCAT(conta_pai,'.',LPAD(numero,length(SUBSTRING_INDEX(SUBSTRING(mascara,length(conta_pai)+2,50),'.',1)),'0'));
                                END ;""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),
    ]
