from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('diario_unico', '0064_Version202109180000'),
    ]
    # Refatorando os contratos para ter um Contrato que agrupa varias Ordens de Registro de Contrato
    operations = [

        migrations.RunSQL("""drop table documento;""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),
        migrations.RunSQL("""CREATE rowstore TABLE documentos (
            id varchar(36) not null,
            estabelecimento varchar(36) not null,
            participante varchar(36) not null,
            token_facilitador varchar(36),
            cnae varchar(7),
            discriminacao varchar(200),
            municipio_prestacao varchar(7),
            numero varchar(20),
            serie varchar(3),
            subserie varchar(3),
            tipo_tributacao_servico varchar(60),
            tipoIss varchar(60),
            emissao date,
            data_registro timestamp,
            modelo varchar(10),
            tenant int,
            sinal varchar(20),
            situacao varchar(30),
            origem varchar(60),
            tipo varchar(60),
            PRIMARY KEY (tenant, id),		
            SHARD KEY(tenant)
        );
""",""),  # Aqui ficaria o SQL para reverter a migration),
        migrations.RunSQL("""drop table diario_unico;""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),

        migrations.RunSQL("""CREATE TABLE diario_unico (
            id varchar(36) not null, 
            tenant int,
            estabelecimento varchar(36) not null, 
            participante varchar(36) not null, 
            cnae varchar(7), 
            documento_numero varchar(20), 
            documento_serie varchar(3), 
            documento_subserie varchar(3), 
            documento_sinal varchar(20),
            documento_id varchar(36), 
            documento_emissao date, 
            documento_tipo varchar(60),
            documento_modelo varchar(10),
            documento_situacao varchar(30),
            item_id varchar(36), 
            item_ordem int,
            item_codigo varchar(40),
            item_descricao varchar(200), 
            data_registro timestamp,
            origem varchar(40),
            tipo_tributacao_servico varchar(40),
            tipoIss varchar(40),
            tipo_tributacao_iss varchar(40), 
            recorrente boolean,
            situacao varchar(40),
            base_iss numeric(20,2),
            aliquota_iss numeric(20,2),
            iss_retido numeric(20,2),
            base_irrf numeric(20,2),
            aliquota_irrf numeric(20,2),
            irrf_retido numeric(20,2),
            base_inss numeric(20,2),
            incidencia_inss numeric(20,2),
            inss_retido numeric(20,2),
            base_csll numeric(20,2),
            aliquota_csll numeric(20,2),
            csll_retido numeric(20,2),
            base_pis numeric(20,2),
            aliquota_pis numeric(20,2),
            pis_retido numeric(20,2),
            base_cofins numeric(20,2),
            aliquota_cofins numeric(20,2),
            cofins_retido numeric(20,2),
            info_pagamento varchar(36), 
            info_cobranca varchar(36), 
            lancamento_ID varchar(36), 
            lancamento_numero int,
            lancamento_data date, 
            lancamento_natureza varchar(20), 
            lancamento_ordem int,
            conta_contabil varchar(30), 
            lancamento_historico varchar(500), 
            valor numeric(20,2), 
            base numeric(20,2),
            percentagem_sobre_base numeric(20,4), 
            momento varchar(30), 
            pasta_contabil varchar(60), 
            codigo_contabil_financeiro varchar(60),
            PRIMARY KEY (tenant, id),		
            SHARD KEY(tenant),
            KEY (tenant, id) USING CLUSTERED COLUMNSTORE
        );""", ""),  # Aqui ficaria o SQL para reverter a migration),

        migrations.RunSQL("""drop table info_cobranca;""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),

        migrations.RunSQL("""CREATE rowstore TABLE info_cobranca (
            id varchar(36) not null,
            tenant int not null,
            vencimento date,
            data_limite_desconto date,
            data_inicio_multa date,
            percentual_desconto numeric(20,4),
            percentual_multa numeric(20,4),
            percentual_juros_diario numeric(20,4),
            valor_bruto numeric(20,4),
            valor_liquido numeric(20,4),
            texto_instrucao varchar(500),
            situacao varchar(60),
            cpf_cnpj_cliente varchar(14),
            nome_cliente varchar(200),
            endereco varchar(200),
            id_cobranca varchar(36),
            id_documento varchar(36),
            numero int,
            nosso_numero varchar(100),
            endereco_cidade varchar(7),
            email varchar(100),
            PRIMARY KEY (tenant, id),		
            SHARD KEY(tenant)
        );""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),
    ]
