import enum

class DocumentoTipo(enum.Enum):
    CONTA_CONSUMO: enum.Enum = 'CONTA_CONSUMO'
    CONTA_ENERGIA: enum.Enum = 'CONTA_ENERGIA'
    CONTA_AGUA_E_ESGOTO: enum.Enum = 'CONTA_AGUA_E_ESGOTO'
    CONTA_GAS: enum.Enum = 'CONTA_GAS'
    COTA_CONDOMINIAL: enum.Enum = 'COTA_CONDOMINIAL'
    FATURA_PRESTACAO_SERVICOS: enum.Enum = 'FATURA_PRESTACAO_SERVICOS'
    GUIA_RETENCAO_PIS = 'GUIA_RETENCAO_PIS'
    GUIA_RETENCAO_COFINS = 'GUIA_RETENCAO_COFINS'
    GUIA_RETENCAO_ICMS = 'GUIA_RETENCAO_ICMS'
    GUIA_RETENCAO_IRRF = 'GUIA_RETENCAO_IRRF'
    GUIA_RETENCAO_CSLL = 'GUIA_RETENCAO_CSLL'
    GUIA_RETENCAO_ISS = 'GUIA_RETENCAO_ISS'
    SALDO_ANTERIOR = 'SALDO_ANTERIOR'
    RPA = 'RPA'
    FOLHA = 'FOLHA'