# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""CREATE SCHEMA contabilidade;""", ""),
        migrations.RunSQL(
            """CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"""", ""),
        migrations.RunSQL("""
                        CREATE TABLE contabilidade.relatorio_gerencial_contabil
                        (
                            relatorio uuid NOT NULL DEFAULT uuid_generate_v4(),
                            tipo smallint NOT NULL,
                            tenant bigint NOT NULL,
                            dia_processamento integer NOT NULL,
                            ultimo_processamento date,
                            estabelecimento character varying(16) NOT NULL,
                            entrada json,
                            email character varying(160),
                            CONSTRAINT relatorio_gerencial_contabil_pkey PRIMARY KEY(relatorio),
                            CONSTRAINT relatorio_dia_processamento_check CHECK(dia_processamento >= 1 AND dia_processamento <= 28)
                        )
                       """, ""),
        migrations.RunSQL("""
            CREATE TABLE contabilidade.servico_relatorio
            (
                tipo smallint NOT NULL,
                tenant bigint NOT NULL,
                url_servico character varying(160) NOT NULL,
                CONSTRAINT servico_relatorio_pkey PRIMARY KEY(tipo, tenant)
            )
            """, "")
    ]
