# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_VersionContabilidade201908060900'),
    ]

    operations = [
        migrations.RunSQL("""
        ALTER TABLE contabilidade.relatorio_gerencial_contabil RENAME TO relatorios_contabeis;
      """, ""),
    ]
