# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_VersionContabilidade201908140957'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO contabilidade.parametros_analise_contabil (parametro_analise_contabil,tenant,dia_alerta,dia_fechamento,ultimo_alerta,ultimo_fechamento,estabelecimento,email) VALUES
        ('a086983c-8a54-45a9-bbc2-6383c8cbb041',47,27,28,NULL,NULL,'20','carlosbenevides@nasajon.com.br');
      """, ""),
        migrations.RunSQL("""
                          INSERT INTO contabilidade.relatorios_contabeis(relatorio, tipo, tenant, dia_processamento, ultimo_processamento, estabelecimento, entrada, email) VALUES
                          ('9d25d8a7-53e5-4ee6-b266-42cdfffcbe6a', 0, 47, 28,
                           NULL, '20', NULL, 'carlosbenevides@nasajon.com.br')
                          """, ""),

    ]
