# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_VersionContabilidade201909041432'),
    ]

    operations = [
        migrations.RunSQL("""CREATE SCHEMA contratos_pagamentos;  """, ""),
        migrations.RunSQL(
            """CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\" """, ""),
        migrations.RunSQL("""
                        CREATE TABLE contratos_pagamentos.contrato
                        (
                            contrato uuid NOT NULL DEFAULT uuid_generate_v4(),
                            codigo character varying(60) NOT NULL,
                            tipo smallint NOT NULL DEFAULT 0,
                            codigo_transacao character varying(150) NOT NULL,
                            estabelecimento character varying(16) NOT NULL,
                            fornecedor character varying(16) NOT NULL,
                            tenant bigint NOT NULL,
                            ultimo_processamento date,
                            modelo_documento json NOT NULL,
                            heuristica_valor smallint NOT NULL,
                            valor numeric(20, 2),
                            CONSTRAINT contrato_pk PRIMARY KEY(contrato)
                        )
                        """, ""),
        migrations.RunSQL("""
                          CREATE TABLE contratos_pagamentos.servico_persistencia_contrato
                          (
                              tenant bigint,
                              codigo_transacao character varying(150),
                              url_servico character varying(150),
                              CONSTRAINT servico_persistencia_contrato_pkey PRIMARY KEY(tenant, codigo_transacao)
                          )
                          """, ""),
    ]
