# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_VersionContratosPagamentos201907170900'),
    ]

    operations = [
        migrations.RunSQL("""
      alter table contratos_pagamentos.servico_persistencia_contrato add column url_persistencia character varying(150);
    """, ""),
        migrations.RunSQL("""
      alter table contratos_pagamentos.servico_persistencia_contrato add column url_listagem character varying(150);
    """, ""),
        migrations.RunSQL("""
      alter table contratos_pagamentos.servico_persistencia_contrato drop column url_servico;
    """, ""),
    ]
