# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_VersionContratosPagamentos201908071941'),
    ]

    operations = [
        migrations.RunSQL("""
      alter table contratos_pagamentos.contrato add column dia_vencimento integer NOT NULL DEFAULT 1;
    """, ""),
        migrations.RunSQL("""
                          ALTER TABLE contratos_pagamentos.contrato ADD CONSTRAINT contrato_dia_vencimento_check CHECK(dia_vencimento >= 1 AND dia_vencimento <= 28)
                          """, ""),
    ]
