# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_VersionContratosPagamentos201908291550'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO contratos_pagamentos.contrato (contrato,codigo,tipo,codigo_transacao,estabelecimento,fornecedor,tenant,ultimo_processamento,modelo_documento,heuristica_valor,valor,dia_vencimento,dia_apropriacao) VALUES
        ('c9f47b8f-c06d-4ff7-95cb-4b5d076da342','0889550',3,'CONTA_GAS','20','33938119000169',47,NULL,'{
        \"numero\": \"1\",
        \"descricao_item\": \"Gas\",
        \"tipo_item\": \"1000\"
        }',1,1000.00,25,1)
    """, ""),
        migrations.RunSQL("""
                          INSERT INTO contratos_pagamentos.contrato(contrato, codigo, tipo, codigo_transacao, estabelecimento, fornecedor, tenant, ultimo_processamento, modelo_documento, heuristica_valor, valor, dia_vencimento, dia_apropriacao) VALUES
                          ('806c8768-9de5-41aa-b97c-31c1aff2dba9', '1935179', 2, 'CONTA_AGUA', '20', '33352394000104', 47, NULL, '{"numero\": \"1\",
                                                                                                                                   \"descricao_item\": \"Agua e Esgoto\",
                                                                                                                                   \"tipo_item\": \"1000\"
                                                                                                                                   }', 1, 1000.00, 25, 1)
                          """, ""),
        migrations.RunSQL("""
                          INSERT INTO contratos_pagamentos.contrato(contrato, codigo, tipo, codigo_transacao, estabelecimento, fornecedor, tenant, ultimo_processamento, modelo_documento, heuristica_valor, valor, dia_vencimento, dia_apropriacao) VALUES
                          ('d41ad200-0695-4a1d-a16f-ec3306b6b7a5', '22963126', 1, 'CONTA_ENERGIA', '20', '16524275634712', 47, NULL, '{\"numero\": \"1\",
                                                                                                                                       \"descricao_item\": \"Agua e Esgoto\",
                                                                                                                                       \"tipo_item\": \"1000\"
                                                                                                                                       }', 1, 1000.00, 25, 1)
                          """, ""),
        migrations.RunSQL("""
                          INSERT INTO contratos_pagamentos.servico_persistencia_contrato(tenant, codigo_transacao, url_persistencia, url_listagem) VALUES
                          (47, 'CONTA_ENERGIA', 'api/47/conta_consumo',
                           'api/47/contas_consumo')
                          """, ""),
        migrations.RunSQL("""
    INSERT INTO contratos_pagamentos.servico_persistencia_contrato(tenant, codigo_transacao, url_persistencia, url_listagem) VALUES
    (47, 'CONTA_GAS', 'api/47/conta_consumo', 'api/47/contas_consumo');
    """, ""),
        migrations.RunSQL("""
                          INSERT INTO contratos_pagamentos.servico_persistencia_contrato(tenant, codigo_transacao, url_persistencia, url_listagem) VALUES
                          (47, 'CONTA_AGUA', 'api/47/conta_consumo',
                           'api/47/contas_consumo')
                          """, "")
    ]
