# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_VersionContratosPagamentos201909041421'),
    ]

    operations = [
        migrations.RunSQL("""CREATE SCHEMA faturamento; """, ""),
        migrations.RunSQL(
            """CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\" """, ""),
        migrations.RunSQL("""
                        CREATE TABLE faturamento.contrato
                        (
                            contrato uuid NOT NULL DEFAULT uuid_generate_v4(),
                            tipo smallint NOT NULL,
                            codigo character varying(16) NOT NULL,
                            estabelecimento character varying(16) NOT NULL,
                            tenant bigint NOT NULL,
                            ultima_faturacao date,
                            modelo_documento json NOT NULL,
                            CONSTRAINT contrato_pk PRIMARY KEY(contrato)
                        )
                        """, ""),
        migrations.RunSQL("""CREATE TABLE faturamento.item_contrato
                        (
                            item_contrato uuid NOT NULL DEFAULT uuid_generate_v4(),
                            contrato uuid NOT NULL,
                            valor numeric(20, 2),
                            tenant bigint NOT NULL,
                            CONSTRAINT item_contrato_pkey PRIMARY KEY(item_contrato),
                            CONSTRAINT contrato_fk FOREIGN KEY(contrato)
                            REFERENCES faturamento.contrato(contrato) MATCH SIMPLE
                            ON UPDATE CASCADE ON DELETE CASCADE
                        )
                        """, ""),
        migrations.RunSQL("""CREATE INDEX fki_item_contrato_fk
                        ON faturamento.item_contrato
                        USING btree
                        (contrato)
                        """, ""),
        migrations.RunSQL("""CREATE TABLE faturamento.contrato_participante
                        (
                            contrato_participante uuid NOT NULL DEFAULT uuid_generate_v4(),
                            contrato uuid NOT NULL,
                            participante character varying(16) NOT NULL,
                            participacao numeric(20, 4),
                            tenant bigint NOT NULL,
                            ultima_faturacao date,
                            CONSTRAINT contrato_participante_pkey PRIMARY KEY(contrato_participante),
                            CONSTRAINT contrato_participante_fk FOREIGN KEY(contrato)
                            REFERENCES faturamento.contrato(contrato) MATCH SIMPLE
                            ON UPDATE CASCADE ON DELETE CASCADE
                        )
                        """, ""),
        migrations.RunSQL("""CREATE INDEX fki_contrato_participante_fk
                        ON faturamento.contrato_participante
                        USING btree
                        (contrato)
                        """, ""),
    ]
