# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_VersionFaturamento201907161115'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE TABLE faturamento.servico_persistencia_contrato
        (
          tenant bigint,
          codigo_transacao character varying(150),
          url_servico character varying(150),
          CONSTRAINT servico_persistencia_contrato_pkey PRIMARY KEY (tenant, codigo_transacao)
        );        
      """, ""),
    ]
