# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_VersionFaturamento201907221129'),
    ]

    operations = [
        migrations.RunSQL("""
      alter table faturamento.contrato_participante drop column ultima_faturacao;
    """, ""),

        migrations.RunSQL("""
                          alter table faturamento.contrato_participante add column ultimo_processamento date
                          """, ""),
    ]
