# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_VersionFaturamento201908011530'),
    ]

    operations = [
        migrations.RunSQL("""
        ALTER TABLE faturamento.regua_cobranca_etapa ALTER COLUMN template_email TYPE varchar(500) USING template_email::varchar;
      """, ""),
    ]
