# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_VersionFaturamento201909041422'),
    ]

    operations = [
        migrations.RunSQL("""
      ALTER TABLE faturamento.contrato ADD ultima_previsao date NULL;
      """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.item_contrato ADD heuristica_valor smallint NULL;
      """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.contrato_participante ADD ultima_previsao date NULL;
      """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.servico_persistencia_contrato ADD url_listagem varchar(150) NULL;
      """, ""),
        migrations.RunSQL("""
      update faturamento.servico_persistencia_contrato set url_listagem = 'api/47/cotas_condominiais';
      """, ""),
    ]
