# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_VersionFaturamento201909131934'),
    ]

    operations = [
        migrations.RunSQL(
            """alter table faturamento.item_contrato add column sufixo varchar(30) ;""", ""),
    ]
