# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_VersionFaturamento201910010909'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE public.log_auxiliar_job (
            tenant int NOT NULL,
            identificador_compromisso varchar(36) NOT NULL,
            participante varchar(36) NOT NULL,
            estabelecimento varchar(36) NOT NULL,
            pasta_contabil varchar(60) NOT NULL,
            momento varchar(60) NOT NULL,
            datahora timestamp NOT NULL DEFAULT now(),
            etapa varchar(60),
            referencia varchar(60),
            log_auxiliar_job uuid NOT NULL DEFAULT uuid_generate_v4(),
            CONSTRAINT log_auxiliar_job_pk PRIMARY KEY (log_auxiliar_job)
        );
        """, ""),
        migrations.RunSQL(
            """ALTER TABLE faturamento.contrato ADD pasta_contabil varchar(60) NULL; """, ""),
        migrations.RunSQL(
            """ALTER TABLE faturamento.item_contrato ADD codigo varchar(50) NULL;""", ""),
    ]
