# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_VersionFaturamento201912161615'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE tenants
        (
         tenant bigserial NOT NULL,
         nome character varying(200),
         codigo character varying(30),
         CONSTRAINT "PK_tenants_tenant" PRIMARY KEY (tenant)
        )""", ""),
    ]
