# Generated by Django 2.2.5 on 2020-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_VersionContabilidade201908060855'),
    ]

    operations = [
        migrations.RunSQL("""
      CREATE TABLE contabilidade.parametros_analise_contabil
      (
        parametro_analise_contabil uuid NOT NULL DEFAULT uuid_generate_v4(),
        tenant bigint NOT NULL,
        dia_alerta integer NOT NULL,
        dia_fechamento integer NOT NULL,
        ultimo_alerta date,
        ultimo_fechamento date,
        estabelecimento character varying(60) NOT NULL,
        email character varying(160),
        CONSTRAINT parametros_analise_contabil_pkey PRIMARY KEY (parametro_analise_contabil),
        CONSTRAINT parametros_analise_contabil_dia_alerta_check CHECK (dia_alerta >= 1 AND dia_alerta <= 28),
        CONSTRAINT parametros_analise_contabil_dia_fechamento_check CHECK (dia_fechamento >= 1 AND dia_fechamento <= 28)
      );
      """, ""),
        migrations.RunSQL("""
                        CREATE TABLE contabilidade.fechamento
                        (
                            fechamento uuid NOT NULL DEFAULT uuid_generate_v4(),
                            estabelecimento character varying(60) NOT NULL,
                            mes_fechamento integer NOT NULL,
                            ano_fechamento integer NOT NULL,
                            tenant bigint NOT NULL,
                            CONSTRAINT fechamento_pkey PRIMARY KEY(fechamento),
                            CONSTRAINT fechamento_un UNIQUE(estabelecimento, mes_fechamento, ano_fechamento, tenant)
                        )
                        """, "")
    ]
