# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_VersionFaturamento201907191757'),
    ]

    operations = [
        migrations.RunSQL("""
      alter table faturamento.contrato add column dia_processamento integer not null check (dia_processamento >= 1 and dia_processamento <= 28);
    """, ""),
        migrations.RunSQL("""
      alter table faturamento.contrato add column dia_vencimento integer not null check(dia_vencimento >= 1 and dia_vencimento <= 28);
    """, ""),
        migrations.RunSQL("""
    alter table faturamento.contrato_participante add column dia_processamento integer not null check (dia_processamento >= 1 and dia_processamento <= 28);
    """, ""),
        migrations.RunSQL("""
      alter table faturamento.contrato_participante add column dia_vencimento integer not null check(dia_vencimento >= 1 and dia_vencimento <= 28);
    """, ""),

        migrations.RunSQL("""
      comment on column faturamento.contrato.tipo is '0) Conven��o condominial';
    """, ""),

        migrations.RunSQL("""
      alter table faturamento.contrato drop column ultima_faturacao;
    """, ""),

        migrations.RunSQL("""
      alter table faturamento.contrato add column ultimo_processamento date;
    """, ""),

        migrations.RunSQL("""
      alter table faturamento.contrato add column codigo_transacao character varying(150) NOT NULL;
    """, ""),

        migrations.RunSQL("""
      alter table faturamento.item_contrato add column modelo_item json not null;
    """, ""),
    ]
