# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_VersionFaturamento201908130905'),
    ]

    operations = [
        # faturamento.contrato
        migrations.RunSQL("""
      INSERT INTO faturamento.contrato (contrato, tipo, codigo, estabelecimento, tenant, modelo_documento, dia_processamento, dia_vencimento, ultimo_processamento, codigo_transacao) VALUES(
        '6abb550f-c6d1-42bc-bfd8-609633793926', 0, '01', '20', 47, '{
          \"tipo\": \"4\",
          \"vencimento\": \"10/08/2019\",
          \"emissao\": \"05/08/2019\",
          \"competencia_inicial\": \"01/07/2019\",
          \"competencia_final\": \"30/07/2019\",
          \"situacao\": 1,
          \"valor\": 0,
          \"origem\": 2,
          \"estabelecimento\": \"20\",
          \"participante\": \"\",
          \"juros_mensal\": 0,
          \"multa_atraso\": 0,
          \"usuario\": \"joao\",
          \"desconto\":0,
          \"situacao\": 0,
          \"codigo_transacao\": \"COTA_CONDOMINIAL\",
          \"itens\": [
          ]
      }', 7, 15,null, 'COTA_CONDOMINIAL');
    """, ""),

        # faturamento.contrato_participante - 1
        migrations.RunSQL("""
      INSERT INTO faturamento.contrato_participante(
        contrato_participante, contrato, participante,
        participacao, tenant, dia_vencimento,
        dia_processamento, ultimo_processamento
      ) VALUES(
        '8e049d30-2a76-4f7a-9aa5-7da853e29248', '6abb550f-c6d1-42bc-bfd8-609633793926', '40418600082',
        0.3, 47, 15,
        7, null
      );
    """, ""),

        # faturamento.contrato_participante - 2
        migrations.RunSQL("""
      INSERT INTO faturamento.contrato_participante (
        contrato_participante, contrato, participante,
        participacao, tenant, dia_vencimento,
        dia_processamento, ultimo_processamento
      ) VALUES (
        'de96ba77-8f4e-4b14-9658-3aafe154cfb0', '6abb550f-c6d1-42bc-bfd8-609633793926', '18413642078',
        0.1, 47, 15,
        7, null
      );
    """, ""),

        # faturamento.contrato_participante - 3
        migrations.RunSQL("""
      INSERT INTO faturamento.contrato_participante(
        contrato_participante, contrato, participante,
        participacao, tenant, dia_vencimento,
        dia_processamento, ultimo_processamento
      ) VALUES(
        '18b03203-5acd-41b4-b6b0-9dcbb57f7417', '6abb550f-c6d1-42bc-bfd8-609633793926', '95392069010',
        0.2, 47, 15,
        7, null
      );
    """, ""),

        # faturamento.contrato_participante - 4
        migrations.RunSQL("""
      INSERT INTO faturamento.contrato_participante (
        contrato_participante, contrato, participante,
        participacao, tenant, dia_vencimento,
        dia_processamento, ultimo_processamento
      ) VALUES (
        '82637487-42cd-413f-a54b-0ce641815ea4', '6abb550f-c6d1-42bc-bfd8-609633793926', '31942117060',
        0.2, 47, 15,
        7, null
      );
    """, ""),

        # faturamento.contrato_participante - 5
        migrations.RunSQL("""
      INSERT INTO faturamento.contrato_participante(
        contrato_participante, contrato, participante,
        participacao, tenant, dia_vencimento,
        dia_processamento, ultimo_processamento
      ) VALUES(
        '75b4f125-aafe-465f-a56f-c213d181b3a0', '6abb550f-c6d1-42bc-bfd8-609633793926', '36637320021',
        0.2, 47, 15,
        7, null
      );
    """, ""),

        # faturamento.item_contrato - 1
        migrations.RunSQL("""
      INSERT INTO faturamento.item_contrato (item_contrato, contrato, valor, tenant, modelo_item) VALUES(
      '0f547fa4-34e0-4b5b-946a-577c1864502a', '6abb550f-c6d1-42bc-bfd8-609633793926', 500.00, 47,
      '{
        \"codigo\": \"01\",
        \"descricao\": \"Taxa de condom�nio\",
        \"tipo\": 4000,
        \"valor\": 400,
        \"juros_mensal\": 10,
        \"multa_atraso\": 2,
        \"desconto\":0,
        \"texto_instrucao\": \"Fatura de cota condominial\",
        \"participante\": null,
        \"lancamentos\": [
        ]
      }');
    """, ""),

        # faturamento.item_contrato - 2
        migrations.RunSQL("""
      INSERT INTO faturamento.item_contrato(item_contrato, contrato, valor, tenant, modelo_item) VALUES(
      'bb4c6370-fbfd-434a-a7fc-9bd62ff03c48', '6abb550f-c6d1-42bc-bfd8-609633793926', 500.00, 47,
      '{"codigo\": \"02\",
        \"descricao\": \"Conta de �gua\",
        \"tipo\": 4000,
        \"valor\": 500,
        \"juros_mensal\": 10,
        \"multa_atraso\": 2,
        \"desconto\": 0,
        \"texto_instrucao\": \"Custo de fornecimento de �gua\",
        \"participante\": null,
        \"lancamentos\": [
        ]
      }');
    """, ""),

        # faturamento.item_contrato - 3
        migrations.RunSQL("""
      INSERT INTO faturamento.item_contrato (item_contrato, contrato, valor, tenant, modelo_item) VALUES(
      'c6114ec9-e927-4a71-ab5a-7fda49d745b3', '6abb550f-c6d1-42bc-bfd8-609633793926', 500.00, 47,
      '{
        \"codigo\": \"03\",
        \"descricao\": \"Conta de Energia El�trica\",
        \"tipo\": 4000,
        \"valor\": 600,
        \"juros_mensal\": 10,
        \"multa_atraso\": 2,
        \"desconto\": 0,
        \"texto_instrucao\": \"Custo de fornecimento de energia el�trica\",
        \"participante\": null,
        \"lancamentos\": [
        ]
      }');
    """, ""),

        # faturamento.item_contrato - 4
        migrations.RunSQL("""
      INSERT INTO faturamento.item_contrato(item_contrato, contrato, valor, tenant, modelo_item) VALUES(
      'cc8b0299-270b-46e8-8fdb-bbaadea9a5ad', '6abb550f-c6d1-42bc-bfd8-609633793926', 500.00, 47,
      '{"codigo\": \"04\",
        \"descricao\": \"Conta de G�s Encanado\",
        \"tipo\": 4000,
        \"valor\": 200,
        \"juros_mensal\": 10,
        \"multa_atraso\": 2,
        \"desconto\": 0,
        \"texto_instrucao\": \"Custo de fornecimento de g�s encanado\",
        \"participante\": null,
        \"lancamentos\": [
        ]
      }');
    """, ""),

        # faturamento.servico_persistencia_contrato
        migrations.RunSQL("""
      INSERT INTO faturamento.servico_persistencia_contrato (
        tenant, codigo_transacao, url_servico
      ) VALUES (
        47, 'COTA_CONDOMINIAL', 'api/47/cota_condominial'
      );
    """, ""),
    ]
