# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_VersionFaturamento201909041750'),
    ]

    operations = [
        migrations.RunSQL(
            """update faturamento.contrato set tipo=4 where tenant=47 and contrato='6abb550f-c6d1-42bc-bfd8-609633793926';""", ""),

        migrations.RunSQL("""update contratos_pagamentos.contrato set valor=400 where tenant=47 and contrato='d41ad200-0695-4a1d-a16f-ec3306b6b7a5'
                          """, ""),
        migrations.RunSQL("""update contratos_pagamentos.contrato set valor=600 where tenant=47 and contrato='c9f47b8f-c06d-4ff7-95cb-4b5d076da342'
                          """, ""),
        migrations.RunSQL("""update contratos_pagamentos.contrato set valor=500 where tenant=47 and contrato='806c8768-9de5-41aa-b97c-31c1aff2dba9'
                          """, ""),
    ]
