# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_VersionFaturamento201909111915'),
    ]

    operations = [
        migrations.RunSQL(
            """create table log(data_hora timestamp default now(), nome_job varchar(60), texto varchar);""", ""),
    ]
