# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_VersionFaturamento201909161212'),
    ]

    operations = [
        migrations.RunSQL(
            """alter table log add column level varchar(30);""", ""),
    ]
