# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_VersionFaturamento201912041616'),
    ]

    operations = [
        migrations.RunSQL(
            """alter table log_auxiliar_job alter column identificador_compromisso drop not null;""", ""),
        migrations.RunSQL(
            """alter table log_auxiliar_job alter column tenant drop not null; """, ""),
        migrations.RunSQL(
            """alter table log_auxiliar_job alter column participante drop not null;""", ""),
        migrations.RunSQL(
            """alter table log_auxiliar_job alter column estabelecimento drop not null; """, ""),
        migrations.RunSQL(
            """alter table log_auxiliar_job alter column pasta_contabil drop not null;""", ""),
        migrations.RunSQL(
            """alter table log_auxiliar_job alter column momento drop not null; """, ""),
        migrations.RunSQL(
            """alter table log_auxiliar_job  ADD COLUMN origem VARCHAR(36);""", ""),
    ]
