# Generated by Django 2.2.5 on 2020-02-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_VersionRequisicoes202001291436'),
    ]

    operations = [
        migrations.RunSQL("""CREATE SCHEMA IF NOT EXISTS util;""", ""),
        migrations.RunSQL("""create table util.custom_sequence(
            chave varchar(255) not null,
            tenant bigint not null,
            last_value bigint,
            primary key(tenant, chave)
        )
            """, ""),
    ]
