# Generated by Django 2.2.5 on 2020-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_VersionUtil202001211901'),
    ]

    operations = [
        migrations.RunSQL("""
      ALTER TABLE util.log_assincrono ALTER COLUMN datahora TYPE timestamp USING datahora::timestamp;
    """, "")
    ]
