# Generated by Django 2.2.5 on 2020-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_VersionUtil202003051713'),
    ]

    operations = [
        migrations.RunSQL("""
      ALTER TABLE contabilidade.parametros_analise_contabil DROP COLUMN ultimo_alerta;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE contabilidade.parametros_analise_contabil DROP COLUMN ultimo_fechamento;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE contabilidade.relatorios_contabeis DROP COLUMN ultimo_processamento;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE contratos_pagamentos.contrato DROP COLUMN ultimo_processamento;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.contrato DROP COLUMN ultimo_processamento;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.contrato DROP COLUMN ultima_previsao;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.contrato_participante DROP COLUMN ultimo_processamento;
    """, ""),
        migrations.RunSQL("""
      ALTER TABLE faturamento.contrato_participante DROP COLUMN ultima_previsao;
    """, ""),
    ]
