# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0002_Version201906251200'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE conta_contabil (
                conta_contabil VARCHAR(36) not null,
                plano_contas varchar(30) not null,
                conta_contabil_pai VARCHAR(36),
                codigo varchar(21) not null,
                nome varchar(100) not null,
                grupo int not null,
                natureza varchar(1) not null,
                inicio_vigencia int not null,
                fim_vigencia int,
                tenant integer not null
            )
            ENGINE=InnoDB;
            """,
            ""  # Aqui ficaria o SQL para reverter a migration
        )
        # migrations.RunSQL(
        #     """
        #     """,
        #     ""  # Aqui ficaria o SQL para reverter a migration
        # )
    ]
