# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0005_Version201907071301'),
    ]

    operations = [

        migrations.RunSQL("""
                update pessoas set cpf_cnpj='33050071000158' where descricao = 'ENEL';
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
                update pessoas set cpf_cnpj='33352394000104' where descricao = 'CEDAE';
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
                update pessoas set cpf_cnpj='16524275634712' where descricao = 'LIGHT';
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
                update pessoas set cpf_cnpj='33938119000169' where descricao = 'NATURGY';
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
