# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0008_Version201907160729'),
    ]

    operations = [

        migrations.RunSQL("""
                CREATE TABLE definicoes_lancamentos (
                    definicao_lancamento varchar(36) NOT NULL,
                    evento varchar(60) NOT NULL,
                    numero int not null,
                    natureza varchar(1) NOT NULL,
                    ordem INT NOT NULL,
                    conta varchar(30) NOT NULL,
                    historico varchar(500) NOT NULL,
                    formula varchar(100) NOT NULL,
                    diario_subtipo INT NULL,
                    empresa varchar(36) NULL,
                    ano int NULL,
                    plano_contas varchar(30),
                    tenant int,
                    CONSTRAINT definicoes_lancamentos_PK PRIMARY KEY (definicao_lancamento)
                );
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                CREATE TABLE empresas_segmentos (
                    empresa varchar(36) NOT NULL,
                    segmento INT NOT NULL,
                    tributacao int not null,
                    ano INT NOT NULL,
                    tenant int not null,
                    CONSTRAINT empresas_segmentos_PK PRIMARY KEY (empresa, segmento, tributacao, ano, tenant)
                );
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                CREATE TABLE empresas_plano_contas (
                    empresa varchar(36) NOT NULL,
                    plano_contas varchar(30),
                    ano INT NOT NULL,
                    tenant int not null,
                    CONSTRAINT empresas_segmentos_PK PRIMARY KEY (empresa, plano_contas, ano, tenant)
                );
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
