# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0009_Version201907160730'),
    ]

    operations = [

        migrations.RunSQL("""
                CREATE TABLE empresas (
                    empresa varchar(36) NOT NULL,
                    codigo varchar(16) NOT NULL,
                    tenant int not null,
                    CONSTRAINT empresas_PK PRIMARY KEY (empresa)
                );
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
