# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0010_Version201907160732'),
    ]

    operations = [

        migrations.RunSQL("""
                insert into definicoes_lancamentos(definicao_lancamento,
                                            evento,
                                            numero,
                                            natureza,
                                            ordem,
                                            conta,
                                            historico,
                                            formula,
                                            diario_subtipo,
                                            plano_contas)
                values ('368af54b-5b21-4231-91d5-a36e6b1b0ac6',
                        'APROPRIACAO_CONTA_ENERGIA',
                        1,
                        'D',
                        1,
                        '4.1.1.08.0002',
                        'Despesa com conta de energia elétrica',
                        'valor',
                        1,
                        'CONDOMINIO');
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                insert into definicoes_lancamentos(definicao_lancamento,
                                            evento,
                                            numero,
                                            natureza,
                                            ordem,
                                            conta,
                                            historico,
                                            formula,
                                            diario_subtipo,
                                            plano_contas)
                values ('d59bde3d-2594-47c6-a156-a66fb17983d3',
                        'APROPRIACAO_CONTA_ENERGIA',
                        1,
                        'C',
                        2,
                        '2.1.2.04',
                        'Conta de energia elétrica a pagar',
                        'valor',
                        1,
                        'CONDOMINIO');
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                insert into definicoes_lancamentos(definicao_lancamento,
                                            evento,
                                            numero,
                                            natureza,
                                            ordem,
                                            conta,
                                            historico,
                                            formula,
                                            diario_subtipo,
                                            plano_contas)
                values ('5d3d9a92-c6a4-46a3-9a32-7794c774acf3',
                        'APROPRIACAO_CONTA_AGUA',
                        1,
                        'D',
                        1,
                        '4.1.1.07.0001',
                        'Despesa com conta de água',
                        'valor',
                        1,
                        'CONDOMINIO');
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),



        migrations.RunSQL("""
                insert into definicoes_lancamentos(definicao_lancamento,
                                            evento,
                                            numero,
                                            natureza,
                                            ordem,
                                            conta,
                                            historico,
                                            formula,
                                            diario_subtipo,
                                            plano_contas)
                values ('f553cc7f-593e-4499-aaf4-934138a0b060',
                        'APROPRIACAO_CONTA_AGUA',
                        1,
                        'C',
                        2,
                        '2.1.2.04',
                        'Conta de água a pagar',
                        'valor',
                        1,
                        'CONDOMINIO');
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),



        migrations.RunSQL("""
                insert into definicoes_lancamentos(definicao_lancamento,
                                            evento,
                                            numero,
                                            natureza,
                                            ordem,
                                            conta,
                                            historico,
                                            formula,
                                            diario_subtipo,
                                            plano_contas)
                values ('2ba5b3dd-56d7-464c-b848-3837a1742012',
                        'APROPRIACAO_CONTA_GAS',
                        1,
                        'D',
                        1,
                        '4.1.1.08.0003',
                        'Despesa com conta de gás',
                        'valor',
                        1,
                        'CONDOMINIO');
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),




        migrations.RunSQL("""
                insert into definicoes_lancamentos(definicao_lancamento,
                                            evento,
                                            numero,
                                            natureza,
                                            ordem,
                                            conta,
                                            historico,
                                            formula,
                                            diario_subtipo,
                                            plano_contas)
                values ('e53aeafd-2492-4c51-98f6-51c423785c24',
                        'APROPRIACAO_CONTA_GAS',
                        1,
                        'C',
                        2,
                        '2.1.2.04',
                        'Conta de gás a pagar',
                        'valor',
                        1,
                        'CONDOMINIO');
                """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
