# Generated by Django 2.2.5 on 2020-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0014_Version201907160736'),
    ]

    operations = [

        migrations.RunSQL("""
                alter table diario_unico add column diario_unico_tipo int;
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
               update diario_unico set diario_unico_tipo=diario_universal_tipo;
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""
                alter table diario_unico drop column diario_universal_tipo;
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

    ]
