# Generated by Django 2.2.5 on 2020-01-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0018_Version201907261656'),
    ]

    operations = [
        migrations.RunSQL("""
                update conta_contabil set codigo='3.1.2' where nome='RECEITAS FINANCEIRAS';
                 """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                update conta_contabil set codigo='3.1.2.01' where nome='RECEITAS DE MULTA E ACRESCIMOS MORATORIOS';
             """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                update conta_contabil set codigo='3.1.2.02' where nome='RENDAS DE INVESTIMENTOS TEMPORARIOS NO SFN (sistema financeiro de habitacao)';
             """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""
                update conta_contabil set codigo='3.1.2.03' where nome='LUCRO NA VENDA DE INVESTIMENTOS TEMPORARIOS';
             """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""delete from conta_contabil  where codigo='3.1.1'; """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""delete from conta_contabil  where codigo='3.1.1.01'; """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""delete from conta_contabil  where codigo='3.1.1.02'; """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'f2d9defd-60f9-43a4-884e-c1ac322c6765', '3.1.1', 'RECEITAS CONDOMINIAIS', '3', 'C', 2019, 0, '330dc100-7a70-4d01-a981-e27cef666cde'); """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'c90b7f5b-5fac-4ebe-b124-a7bd843b8331', '3.1.1.01', 'RECEITA DE COTAS CONDOMINIAIS', '3', 'C', 2019, 0, 'f2d9defd-60f9-43a4-884e-c1ac322c6765'); """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""insert into conta_contabil (plano_contas, conta_contabil, codigo, nome, grupo, natureza, inicio_vigencia, tenant, conta_contabil_pai) values ('CONDOMINIO', 'd22f2807-57cd-4abe-b635-6678010c65df', '3.1.1.02', 'RECEITA DE COTAS', '3.1', 'C', 2019, 0, 'f2d9defd-60f9-43a4-884e-c1ac322c6765'); """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
