# Generated by Django 2.2.5 on 2020-01-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0019_Version201907281249'),
    ]

    operations = [
        migrations.RunSQL("""
                alter table documento add column identificador_contrato varchar(36);
             """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
