# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0023_Version201908070930'),
    ]

    operations = [
        migrations.RunSQL("""
                alter table enderecos add column cobranca bool;
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
