# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0024_Version201908071742'),
    ]

    operations = [
        migrations.RunSQL("""
                CREATE TABLE info_pagamento (
                info_pagamento VARCHAR(36) not null,
                documento varchar(36) not null,
                id_operacao VARCHAR(36),
                vencimento date not null,
                mensagem_erro varchar(200),
                situacao int default 0,
                tenant bigint
            )
            ENGINE=InnoDB;
            """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
