# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0027_Version201908121347'),
    ]

    operations = [
        migrations.RunSQL("""alter table info_cobranca drop column documento;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_cobranca add column documento varchar(36);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""alter table info_pagamento drop column documento;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_pagamento add column documento varchar(36);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""alter table info_pagamento drop column id_operacao;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""alter table info_pagamento add column id_operacao varchar(36);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
