# Generated by Django 2.2.5 on 2020-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0041_Version201909161213'),
    ]

    operations = [
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__COTA', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__ENERGIA', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__AGUA', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__GAS', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__MULTAS', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__OBRA', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__RESERVA', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__GARAGEM', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('PAGAMENTO_COTA_CONDOMINIAL__OUTROS', 1, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 4);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__COTA', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__ENERGIA', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__AGUA', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__GAS', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__MULTAS', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__OBRA', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__RESERVA', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__GARAGEM', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""INSERT INTO definicoes_info_cobranca (evento, numero_lancamento, formula_juros_mensal, formula_multa_atraso, formula_desconto, formula_texto_instrucao, formula_vencimento, formula_participante, situacao) VALUES('APROPRIACAO_COTA_CONDOMINIAL__OUTROS', 2, 'juros_mensal', 'multa_atraso', 'desconto', 'texto_instrucao', 'data_pagamento', 'participante', 1);""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

    ]
