# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0042_Version201909161214'),
    ]

    operations = [
        migrations.RunSQL("""update definicoes_lancamentos
                     set conta='3.1.1.02'
                     where evento like '%\_\_ENERGIA' and conta='3.1.1.01'
                     """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
                     set conta='3.1.1.03'
                     where evento like '%\_\_AGUA' and conta='3.1.1.01'
                     """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
                     set conta='3.1.1.04'
                     where evento like '%\_\_GAS' and conta='3.1.1.01'
                     """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
        set conta='3.1.1.05'
        where evento like '%\_\_MULTAS' and conta='3.1.1.01'; """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
                     set conta='3.1.1.06'
                     where evento like '%\_\_OBRAS' and conta='3.1.1.01'
                     """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
                     set conta='3.1.1.07'
                     where evento like '%\_\_RESERVA' and conta='3.1.1.01'
                     """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
                     set conta='3.1.1.08'
                     where evento like '%\_\_GARAGEM' and conta='3.1.1.01'
                     """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""update definicoes_lancamentos
        set conta='3.1.1.09'
        where evento like '%\_\_OUTROS' and conta='3.1.1.01';""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
