# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0045_Version201909251212'),
    ]

    operations = [
        migrations.RunSQL("""alter table empresas add column mascara_contabil character varying(20)""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
