# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0048_Version201910100834'),
    ]

    operations = [
        migrations.RunSQL("""CREATE
                        VIEW vw_timeserver AS SELECT
                        consulta.tempo AS tempo
                        FROM
                        (
                        SELECT
                            DISTINCT SUB.tempo AS tempo
                        FROM
                            (
                            SELECT
                                DATE_ADD(time_service.data_hora_gravada, INTERVAL TIMESTAMPDIFF(SECOND, time_service.ultima_alteracao, NOW()) SECOND) AS tempo
                            FROM
                                time_service as time_service
                        UNION ALL
                            SELECT
                                NOW() AS tempo) AS SUB) AS consulta
                        LIMIT 1""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
