# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0049_Version201911081051'),
    ]

    operations = [
        migrations.RunSQL("""ALTER TABLE diario_unico ADD icms_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD icms_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_icms_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_icms_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD aliquota_icms_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""ALTER TABLE diario_unico ADD pis_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD pis_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_pis_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_pis_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD aliquota_pis_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),



        migrations.RunSQL("""ALTER TABLE diario_unico ADD cofins_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD cofins_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_cofins_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_cofins_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD aliquota_cofins_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),



        migrations.RunSQL("""ALTER TABLE diario_unico ADD csll_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD csll_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_csll_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_csll_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD aliquota_csll_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""ALTER TABLE diario_unico ADD irrf_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD irrf_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_irrf_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_irrf_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD aliquota_irrf_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),


        migrations.RunSQL("""ALTER TABLE diario_unico ADD iss_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD iss_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_iss_retido_original decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD base_iss_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD aliquota_iss_retido decimal(16,2) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
