# Generated by Django 2.2.5 on 2020-01-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0052_Version201912051051'),
    ]

    operations = [
        migrations.RunSQL("""ALTER TABLE documento DROP COLUMN sinal;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE documento DROP COLUMN situacao;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE documento DROP COLUMN origem;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE documento ADD sinal varchar(40) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE documento ADD situacao varchar(40) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE documento ADD origem varchar(40) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""ALTER TABLE diario_unico DROP COLUMN sinal;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico DROP COLUMN situacao;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico DROP COLUMN origem;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD sinal varchar(40) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD situacao varchar(40) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
        migrations.RunSQL("""ALTER TABLE diario_unico ADD origem varchar(40) NULL;""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),
    ]
