# Generated by Django 2.2.5 on 2020-01-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0054_Version201912190912'),
    ]

    operations = [
        migrations.RunSQL("""CREATE VIEW first_day_timeserver AS
                            SELECT
                            CONVERT(tempo + INTERVAL 1 DAY - INTERVAL EXTRACT(DAY from tempo) DAY, date) first_day 
                            FROM vw_timeserver """,  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

        migrations.RunSQL("""CREATE VIEW last_day_timeserver AS
                            SELECT
                            CONVERT(tempo + INTERVAL 1 MONTH - INTERVAL EXTRACT(DAY from tempo) DAY, date) last_day 
                            FROM vw_timeserver""",  ""  # Aqui ficaria o SQL para reverter a migration
                          ),

    ]
