# Generated by Django 2.2.5 on 2020-01-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_unico', '0059_Version202003310748'),
    ]

    operations = [
        migrations.RunSQL("""ALTER TABLE definicoes_lancamentos DROP COLUMN diario_subtipo""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),
        migrations.RunSQL("""ALTER TABLE diario_unico DROP COLUMN diario_unico_subtipo""",
                          ""),  # Aqui ficaria o SQL para reverter a migration),
    ]
