node('aws-codebuild') {
    def buildName = (env.BRANCH_NAME != 'production') ? "${env.BRANCH_NAME}-${BUILD_NUMBER}" : "${BUILD_NUMBER}"
    def PLAYBOOK = "/opt/devops/Ansible/ci.yml"

    stage('Clean') {
        deleteDir()
    }

    stage('Fetch') {
        timeout(time: 60, unit: 'SECONDS') {
            checkout scm
        }
    }

    // stage('Tests') {

	// 	def customImage = docker.build("test-image")

	//     customImage.inside("-u 1000:1000") {
    //         sh 'export skip_log=True'
    //         sh 'python3 -m unittest discover -s ./nasajon -p "test*.py"'
    //     }
	// }
	
	stage('Docker Ship') {
		sh "sudo docker build --no-cache --rm -t hub.nasajon.com.br/pastascontabeis:${buildName} ."
		sh "sudo docker push hub.nasajon.com.br/pastascontabeis:${buildName}"
		sh "sudo docker rmi -f hub.nasajon.com.br/pastascontabeis:${buildName}"
	}

    // if (env.BRANCH_NAME == 'master') {
    //     withCredentials([string(credentialsId: 'KB_CONFIG_FILE_CONTENT_CONDOMINIO', variable: 'KB_CONFIG_FILE_CONTENT')]) {
    //         docker.image('nasajon/kubectl').inside("-u root:root --entrypoint='' -e KB_CONFIG_FILE_CONTENT='$KB_CONFIG_FILE_CONTENT'") {
    //           sh "/exec-kubectl.sh --namespace=pastascontabeis set image deployment api api=hub.nasajon.com.br/pastascontabeis:${buildName} --insecure-skip-tls-verify=true"
	//       sh "/exec-kubectl.sh --namespace=pastascontabeis set image deployment job job=hub.nasajon.com.br/pastascontabeis:${buildName} --insecure-skip-tls-verify=true"
	//       sh "/exec-kubectl.sh --namespace=pastascontabeis set image deployment upgrade-db-diario upgrade-db-diario=hub.nasajon.com.br/pastascontabeis:${buildName} --insecure-skip-tls-verify=true"
	//       sh "/exec-kubectl.sh --namespace=pastascontabeis set image deployment upgrade-db-condominio upgrade-db-condominio=hub.nasajon.com.br/pastascontabeis:${buildName} --insecure-skip-tls-verify=true"    
    //         }
    //     }

    //     // emailext(
    //     //     to: 'cvf@nasajon.com.br',
    //     //     subject: "Build Publicado em QA: '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
    //     //     body: "Build Publicado em QA: '${env.JOB_NAME} [${env.BUILD_NUMBER}]' - Alterações: '${env.BUILD_URL}/changes'"
    //     // )
    // }

    if (env.BRANCH_NAME == 'master') {
        // stage('SonarQube analysis') {
        //     def scannerHome = tool 'SonarQube';
        //     withSonarQubeEnv('Sonar') {
        //         sh "${scannerHome}/bin/sonar-scanner"
        //     }
	    // }

        stage('Deploy QA'){
            sh "ansible-playbook ${PLAYBOOK} -e 'build_path=${WORKSPACE} env=qa'"
        }
    }
    else if (env.BRANCH_NAME == 'production') {
        stage('Pipeline Prod'){
            sh "ansible-playbook ${PLAYBOOK} -e 'build_path=${WORKSPACE} env=prod'"
        }

        // emailext(
        //     to: 'suporte3@nasajon.com.br',
        //     subject: "Liberação Diário Único em Produção: '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        //     body: "Po favor, liberar em produção o novo build do Diário Único: '${env.JOB_NAME} [${env.BUILD_NUMBER}]' - Alterações: '${env.BUILD_URL}/changes'"
        // )
    }
}
